spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
#    内存模式
#    url:  jdbc:h2:mem:base
#   AUTO_SERVER 混合模式 、DB_CLOSE_ON_EXIT、跟随项目启动
    url: jdbc:h2:file:./h2/base-db;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE
    username: root
    password: root
#    每次加载 , 只用于表格创建
#    schema: classpath:db/base.sql
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
